### ISSUE TITLE
Probeer eens ```:focus``` styling!

### ISSUE THREAD

**Issue by itsValyria** [ambersr/all-human-accessible-website#1]
Hey Amber! Super mooie website heb je gemaakt!

Ik had een tip voor jou om je accessibility nog beter te maken! :)

Kijk eens naar ```:focus``` styling, hiermee kun je de focus ring stylen die je ziet bij het tabben van je website.

Kies vooral een lelijke, heldere kleur die niet bij je huisstijl past. Dan is hij extra goed te zien. ;)

[Hier](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus) kun je er meer informatie over lezen.

<img src="https://media4.giphy.com/media/FR6VI9pRlISJX74Wuk/giphy.gif"/>

**Comment by ambersr** [comment]
Thanks voor de tip! Ik heb nu op alle buttons, linkjes, accordion en form velden een :focus toegevoegd. 

Commit: c22f06c592a8ab002f22a927c028b6ceaba11892
Commit: a6c92901c2a473c8ea4501bd217b04075312a849
