### ISSUE TITLE
Kleurcontrast

### ISSUE THREAD

**Issue by irisvw** [ambersr/all-human-accessible-website#2]
De volgende onderdelen voldoen niet aan de AA guidelines voor kleurcontrast:
![image](https://github.com/user-attachments/assets/e36c414b-bc41-4990-b525-de5950b20f07)

Niet zoveel aan te doen omdat het om een huisstijl kleur gaat, maar misschien is het mogelijk om de huisstijl elders te implementeren.

De form placeholders voldoen ook niet aan de AA guidelines, maar zouden wel makkelijk aan te passen zijn.
![image](https://github.com/user-attachments/assets/2babe5f3-854e-4923-b839-6f18c886ee1e)

**Comment by ambersr** [comment]
De huidige kleur van de button heb ik aangepast. De contrast analyzer geeft aan dat de achtergrondkleur i.c.m een dik lettertype geslaagd is voor de test (zie afbeelding). Aangezien dit de huisstijl kleuren zijn van de klant kan ik hier niet veel in aanpassen. Voor een button is het ook belangrijk om goed op te vallen voor SEO doeleinden. De button valt nu nog steeds op en voldoet ook deels aan de richtlijnen van de WCAG-eisen.

Commit: fb83ebc70a3726232bd9bf2a49e206971cc5a7e6

<img width="400" alt="image" src="https://github.com/user-attachments/assets/605f81eb-d649-4e84-b3d1-e1bf68b531a4">

**Comment by ambersr** [comment]
- De huidige kleur van de button heb ik aangepast. De contrast analyzer geeft aan dat de achtergrondkleur i.c.m een dik lettertype geslaagd is voor de test (zie afbeelding). Aangezien dit de huisstijl kleuren zijn van de klant kan ik hier niet veel in aanpassen. Voor een button is het ook belangrijk om goed op te vallen voor SEO doeleinden. De button valt nu nog steeds op en voldoet ook deels aan de richtlijnen van de WCAG-eisen.

Commit: fb83ebc70a3726232bd9bf2a49e206971cc5a7e6

<img width="400" alt="image" src="https://github.com/user-attachments/assets/605f81eb-d649-4e84-b3d1-e1bf68b531a4">

- De tekst in de input heeft een donkere kleur gekregen. Deze voldoet nu aan de WCAG-eisen (zie afbeelding).

Commit: b3e8e03e043caf17271166596e965a04692c7852

<img width="400" alt="image" src="https://github.com/user-attachments/assets/5e7a2b31-0da4-40eb-8579-c69150dc1f94">
