### ISSUE TITLE
:focus styling ontbreekt bij "belangrijke informatie"

### ISSUE THREAD

**Issue by irisvw** [ambersr/all-human-accessible-website#3]
![image](https://github.com/user-attachments/assets/d31c0d51-1da0-4daf-82df-78e46ee97d45)

Hier ontbreekt focus styling, waardoor niet duidelijk is welk element in focus is.

Misschien handig: je zou het `<details>` element kunnen gebruiken voor de accordion :)
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

**Comment by ambersr** [comment]
Ik heb de form nu opgebouwd met een detail en een summary. Deze heb ik ook een focus gegeven. Als je met tab de accordion wilt openen bevat het een opvallende kleur wanneer het actief is. 

Bedankt voor de tip!

Commit :focus accordion: c22f06c592a8ab002f22a927c028b6ceaba11892
Commit accordion andere opbouw: d136b33aca130eb81869feca6b0d2c20776472b2
