### ISSUE TITLE
Image alt texts

### ISSUE THREAD

**Issue by irisvw** [ambersr/all-human-accessible-website#4]
Voor de blaadjes op de achtergrond zou het misschien beter zijn om de alt text leeg te laten, omdat deze alleen decoratief zijn en afleiden van de content. 
Ook de alt text op de pijltjes op de buttons zou ik weghalen. Voor screenreaders is het al duidelijk dat het een link is.

**Comment by ambersr** [comment]
Bedankt voor de tip! Ik heb de alt attributen leeggemaakt.

Commit: 5ac0ad0ab059aafff5af55c8cf15a0779c5ee6ed
