### ISSUE TITLE
Content sectioning

### ISSUE THREAD

**Issue by irisvw** [ambersr/all-human-accessible-website#5]
De footer staat op dit moment in de `<main>`, misschien is het voor de structuur beter/overzichtelijker als deze daarbuiten staat.

**Comment by ambersr** [comment]
Ik heb de footer uit de main gehaald. Dit is inderdaad beter voor de structuur en het schrijven van semantieke code.

Commit: 1e11a0fcaff6548933411344f24cd3eeb07cc6dd

**Comment by ambersr** [comment]
Ik heb de footer uit de main gehaald. Dit is inderdaad beter voor de structuur en het schrijven van semantieke code.

Commit: 1e11a0fcaff6548933411344f24cd3eeb07cc6dd
