### ISSUE TITLE
Code review toegankelijkheid | 18 oktober 2024 | Door Karima Mouadi en Robin Wouterson

### ISSUE THREAD

**Issue by Karima002** [ambersr/all-human-accessible-website#7]
De validator geeft geen errors, complimenten!

Typfout in de class denk ik:
https://github.com/ambersr/all-human-accessible-website/blob/f60149d9b9c26e87ddecf713e63152e7d758056e/index.html#L49

Er zit hier een `<header>` in de `<main>`.
https://github.com/ambersr/all-human-accessible-website/blob/f60149d9b9c26e87ddecf713e63152e7d758056e/index.html#L39-L47
Meer info vind je hier: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main

Voor de rest ziet het er goed uit! Ga zo door

Code review gegeven door @Robinwouterson en @karima002

**Comment by ambersr** [comment]
Ik heb de header element vervangen voor een section element!

Commit: 1736a2ad45590b0fddc5d66d7602d0a918cb4e0a
