### ISSUE TITLE
# Amber feedback

### ISSUE THREAD

**Issue by fatimahilali** [ambersr/all-human-accessible-website#8]
Header Structuur:
Het is goed dat je de headers in de juiste volgorde hebt gebruikt (h1, h2, h3, enzovoort). Dit maakt het makkelijker voor schermlezers om de inhoud te begrijpen en de structuur van de pagina te volgen. [Bekijk hier regel 50](https://github.com/ambersr/all-human-accessible-website/blob/a6c92901c2a473c8ea4501bd217b04075312a849/index.html#L50) en [hier regel 109](https://github.com/ambersr/all-human-accessible-website/blob/a6c92901c2a473c8ea4501bd217b04075312a849/index.html#L109).

Alt-teksten:
Zorg ervoor dat je overal waar nodig de alt-tekst gebruikt. Dit helpt de schermlezer om te begrijpen wat elk element doet en wat de functie ervan is. [Bekijk hier regel 105](https://github.com/ambersr/all-human-accessible-website/blob/a6c92901c2a473c8ea4501bd217b04075312a849/index.html#L105) 

Gebruik van ARIA:

Goed dat je  aria-labelledby gebruikt bij de FAQ-sectie. Als je echter goede en semantische HTML gebruikt, is het vaak niet nodig om ARIA-labels te gebruiken. Bekijk hier regel [128](https://github.com/ambersr/all-human-accessible-website/blob/a6c92901c2a473c8ea4501bd217b04075312a849/index.html#L128).

CSS-variabelen:
Goed dat je CSS-variabelen voor kleuren gebruikt! Dit maakt je code makkelijker te onderhouden. [Bekijk hier regels 1 tot en met 8](https://github.com/ambersr/all-human-accessible-website/blob/a6c92901c2a473c8ea4501bd217b04075312a849/styles/styles.css#L1C1-L8C2).

Media Queries:
De media queries zijn goed, maar gebruik @media (min-width: 820px) in plaats van @media (width > 820px). Dit zorgt voor betere responsiviteit.

Z-index:
Kijk uit met het te veel gebruiken van z-index. Dit kan leiden tot lay-outproblemen, zoals overlapping van elementen, waardoor belangrijke inhoud onzichtbaar kan worden .

Te veel gebruik van Media Queries:

Er zijn te veel media queries gebruikt waar dat niet nodig is. Maak je code responsief zodat je minder media queries nodig hebt. Gebruik ook geen px, maar gebruik eenheden zoals vh, rem, clamp() of %. Dit maakt je code al een stuk responsiever. [Bekijk hier regels 60 tot en met 86](https://github.com/ambersr/all-human-accessible-website/blob/a6c92901c2a473c8ea4501bd217b04075312a849/styles/styles.css#L60C1-L86C1).

Voor de .nav-geveltuin heb je  bijvoorbeeld geen media query nodig. De code kan er als volgt uitzien:

.nav-geveltuin {
    display: flex;
    justify-content: space-between;
    align-items: center;
    background-color: var(--beige-background);
    color: #481B02;
    padding: 2vw; 
    transition: top 0.3s;
    position: fixed;
    width: 100%;
    overflow: hidden;
    z-index: 99;
}
Door de padding in viewport breedte (vw) in te stellen, past de padding zich automatisch aan naarmate de breedte van het scherm verandert, wat zorgt voor een responsieve lay-out zonder meerdere media queries.

**Comment by ambersr** [comment]
Thanks voor je feedback!! Ik heb het meegenomen en naar gekeken. 

Het volgende heb ik aangepast:
- Ik heb een aantal ARIA elementen eruit gehaald, er waren er inderdaad veel overbodig.
- De benaming van media queries aangepast naar media (min-width: 820px).
- Overbodige alt-teksten eruit gehaald.

De z-index heb ik nodig om elementen over elkaar heen te plaatsen (zie ontwerp). Voor de volgende keer ga ik kijken of ik de media queries minder kan gebruiken. Voor nu werkt dit erg goed op verschillende schermbreedtes dus deze laat ik staan.
